-- Seed track catalog from legacy SQLite database.
-- This migration is idempotent and safe to re-run.

INSERT INTO russian (id, artist, name, path) VALUES
    (1, '10AGE', 'Нету Интереса (ShaHriX Remix)', 'CQACAgIAAxkBAAKkKGlo5pbFR5WdPo6NeYeDbkJir5yyAAJqlgACt2hIS8h2Jj0tFhvOOAQ'),
    (2, '10AGE', 'Паравозик (ShaHriX Remix)', 'CQACAgIAAxkBAAKkKWlo5pZ-fWcIdZWSlq9LGIBN_wmzAAJrlgACt2hIS5JvQg2JV7gxOAQ'),
    (3, '10AGE', 'Пушка (ShaHriX Remix)', 'CQACAgIAAxkBAAKkKmlo5pbkIdhNgWIbHrj5Z6HAxJPCAAJslgACt2hIS6ZCw8my9RlBOAQ'),
    (4, 'ALEKS ATAMAN', 'Диалоги тет-а-тет (ShaHriX Remix)', 'CQACAgIAAxkBAAKkVWlo5-UxBzE7hSoLAAHWzmjD7WfJDAACgZYAArdoSEvtcEOCiKhXMDgE'),
    (5, 'ALEKS ATAMAN', 'ОЙОЙОЙ (ТЫ ГОВОРИЛА) (ShaHriX Remix)', 'CQACAgIAAxkBAAKkVmlo5-VR6Lm6mTF4j61gN7n8RCKbAAKClgACt2hIS5uvJDTPzBCQOAQ'),
    (6, 'AMURA', 'Как Дела (ShaHrix Remix)', 'CQACAgIAAxkBAAKkWWlo6GTaIoN2YRbgffewagJsCnnSAAKQlgACt2hIS2iT843zYYfSOAQ'),
    (7, 'AMURA', 'Хотелось бросить (ShaHriX Remix)', 'CQACAgIAAxkBAAKkW2lo6GV9UY80C9CfbX9FBgqoOQ5_AAKRlgACt2hIS_Gs7-yqqAvSOAQ'),
    (8, 'ANDRO', 'X.O (ShaHriX Remix)', 'CQACAgIAAxkBAAKkXWlpHbkc4puWf459iSOSy1yLe5t2AAJJmgACt2hIS2XcH-kkr1IDOAQ'),
    (9, 'ANDRO', 'Другому (ShaHriX Remix)', 'CQACAgIAAxkBAAKkXmlpHbrZ-vtlkqNBKOKl0zAv2BIEAAJLmgACt2hIS7gL-j4hZrBTOAQ'),
    (10, 'ANDY PANDA', 'All The Time (ShaHriX Remix)', 'CQACAgIAAxkBAAKkbGlpHh_qFUJAd0t-oOMbf1qHDngdAAJWmgACt2hIS1YnrYpxZBVGOAQ'),
    (11, 'ANDY PANDA', 'Marmelade (ShaHriX Remix)', 'CQACAgIAAxkBAAKkbmlpHiEp1Fw6zDDHJkNqO_bUuNakAAJXmgACt2hIS3zb2EBI4ukPOAQ'),
    (12, 'ANDY PANDA', 'Патрон (ShaHriX Remix)', 'CQACAgIAAxkBAAKkcGlpHif8XJ1Em3e2Lyqi4K0lxphFAAJYmgACt2hIS58DruXdnpMOOAQ'),
    (13, 'ANDY PANDA', 'Санавабич (ShaHriX Remix)', 'CQACAgIAAxkBAAKkcmlpHicMjc2qmWYCeKeQyQff2_FyAAJZmgACt2hISxHS9o3mb0XzOAQ'),
    (14, 'ANDY PANDA', 'Там Ревели Горы (ShaHriX Remix)', 'CQACAgIAAxkBAAKkdGlpHicUaKOZOBi916XQojFL2QABdAACWpoAArdoSEvRF3GUlaZWUDgE'),
    (15, 'A.V.G', '25 Кадр (ShaHriX Remix)', 'CQACAgIAAxkBAAKkhGlpHoG4SGA2Urz25XzTv5hhxKHCAAJjmgACt2hISw_Dztd1nhKMOAQ'),
    (16, 'A.V.G', 'Она Кайф (ShaHriX Remix)', 'CQACAgIAAxkBAAKkhmlpHoP_vDcO7VIN5sQHxE2VeK76AAJkmgACt2hISxkNJhKJ9QXkOAQ'),
    (17, 'A.V.G', 'Платина (ShaHriX Remix)', 'CQACAgIAAxkBAAKkiGlpHoUXtpH8BbWNTyezFEh527ttAAJnmgACt2hIS4glj-EVSPEBOAQ'),
    (18, 'A.V.G', 'С тобой (ShaHriX Remix)', 'CQACAgIAAxkBAAKkimlpHojlWd4U5D7SC6JLTtDkAAEhOgACaJoAArdoSEtbRrP2EYWPijgE'),
    (19, 'BAKR', 'За Любовь (ShaHriX Remix)', 'CQACAgIAAxkBAAKkjGlpIQTEvsINlIUy-Qwx56meoqePAAKbmgACt2hIS2zGrdhIgi0yOAQ'),
    (20, 'BRANYA', 'Пополам (ShaHriX Remix)', 'CQACAgIAAxkBAAKkjmlpIRfdNlSbfhccn6YmiVH-idSXAAKemgACt2hIS_THARL3XMH6OAQ'),
    (21, 'CVETOCEK7', 'Все ссоры надоели (ShaHriX Remix)', 'CQACAgIAAxkBAAKkkGlpIT_PMjGng2abSOWeXx8I8DNlAAKgmgACt2hIS3a7X3ZIZZ-tOAQ'),
    (22, 'CVETOCEK7', 'Седая Ночь (ShaHriX Remix)', 'CQACAgIAAxkBAAKkkmlpIUSKPJIqGCSIDNV-XfyBtlMrAAKhmgACt2hIS6ku_fH2XTThOAQ'),
    (23, 'DAREEM', 'Новый Год (ShaHriX Remix)', 'CQACAgIAAxkBAAKklGlpIXbmR2y7dBaS2ZTgIOCbmxFUAAKjmgACt2hISyCVwDfUWqBqOAQ'),
    (24, 'ELMAN', 'Морозы (ShaHriX Remix)', 'CQACAgIAAxkBAAKklmlpIYMakbka4U8GSegPp1BQu-30AAKlmgACt2hIS_9UXjXoP3n_OAQ'),
    (25, 'ELMAN', 'Балкон (ShaHriX Remix)', 'CQACAgIAAxkBAAKkmGlpIYh_hQhdr3NBnhddzOm0YGhbAAKmmgACt2hIS3irzOIORMrGOAQ'),
    (26, 'ELMAN', 'Черная Любовь (ShaHriX Remix)', 'CQACAgIAAxkBAAKkmmlpIYh_zo7VyitX-wIRscS4NXU2AAKnmgACt2hIS7pDRzqGg7yaOAQ'),
    (27, 'ESCAPE', 'Не Смотри (ShaHriX Remix)', 'CQACAgIAAxkBAAKknGlpIY77iE9VlJ-d5Hd__HJnu99AAAKpmgACt2hISwxfcPWqlzqSOAQ'),
    (28, 'GAFUR', 'Морозы (ShaHriX Remix)', 'CQACAgIAAxkBAAKknmlpIaBsRwfCDPwY39Ic2qpZG-VlAAKrmgACt2hIS7oRqEBY0vmFOAQ'),
    (29, 'GAFUR', 'Ok (ShaHriX Remix)', 'CQACAgIAAxkBAAKkoGlpIaJDAbDJLJraS6_smH3zXNS2AAKsmgACt2hIS-QXDd1DlGhLOAQ'),
    (30, 'GAFUR', 'Атом (ShaHriX Remix)', 'CQACAgIAAxkBAAKkomlpIaPbTRtckx7Gq9oM6xE1eDPwAAKtmgACt2hIS12B9U7_05AlOAQ'),
    (31, 'GIDAYYAT', 'Лунная (ShaHriX Remix)', 'CQACAgIAAxkBAAKkpGlpIa_DEY9JD2ow2-TCUcOPV0BbAAKvmgACt2hIS4IyaOinBRFLOAQ'),
    (32, 'GUMA', 'Стеклянная (ShaHriX Remix)', 'CQACAgIAAxkBAAKkpmlpIbaFEDH774Sp9HmVk9ldR1iaAAKwmgACt2hIS4KqAWn6hFWPOAQ'),
    (33, 'HENSY', 'Костер (ShaHriX Remix)', 'CQACAgIAAxkBAAKkqGlpIcOtmqwVUURl-mZq_McPzAVxAAKxmgACt2hIS0_pOzINrIDAOAQ'),
    (34, 'ILETRE', 'Седая Ночь (ShaHriX Remix)', 'CQACAgIAAxkBAAKkqmlpIc0ceihwKVx5rcPedsrPh3dEAAKymgACt2hIS2WYy5-eFvj6OAQ'),
    (35, 'INSTASAMKA', 'На Титанике (ShaHriX Remix)', 'CQACAgIAAxkBAAKkrGlpIeT_q0bN8LgunH4IRjVz_hydAAK2mgACt2hISyMgtpZZaSMOOAQ'),
    (36, 'JAKOMO', 'Платина (ShaHriX Remix)', 'CQACAgIAAxkBAAKkrmlpIfdIpEiN8tBnDnZQ27K6fgI-AAK5mgACt2hIS6II70Osy0M1OAQ'),
    (37, 'JAMIK', 'Франция (ShaHriX Remix)', 'CQACAgIAAxkBAAKksGlpIgabmnA60ISwb-84kRZbv62uAAK6mgACt2hIS4Cz24qKfXQYOAQ'),
    (38, 'JANAGA', 'По Щекам Слезы (ShaHriX Remix)', 'CQACAgIAAxkBAAKksmlpIhO_xxP9GtLRdzCOzpRPs8aMAAK9mgACt2hIS64pquGZ4OmrOAQ'),
    (39, 'JONY', 'Аллея (ShaHriX Remix)', 'CQACAgIAAxkBAAKktGlpIh0zWpkIJ9UjAqFO50-Moj5VAAK_mgACt2hIS4Y2bsqbaOktOAQ'),
    (40, 'JONY', 'Балкон (ShaHriX Remix)', 'CQACAgIAAxkBAAKktmlpIh5eIpvHwgh4UDDIL4OIZfEcAALAmgACt2hIS11zkAkX15NNOAQ'),
    (41, 'JONY', 'Камнепад (ShaHriX Remix)', 'CQACAgIAAxkBAAKkuGlpIiQ0Efpm6tG9FVS0WcyPut0cAALCmgACt2hISx-mFJtno1D6OAQ'),
    (42, 'JONY', 'Наверно Ты Меня Не Помнишь (ShaHriX Remix)', 'CQACAgIAAxkBAAKkumlpIiRzb6WGIFFwmTQcdROXGlpBAALDmgACt2hIS4zMp2Di4r36OAQ'),
    (43, 'JONY', 'Небесные Розы (ShaHriX Remix)', 'CQACAgIAAxkBAAKkvGlpIiTjkUTAn5RRgozLwD9e3byaAALEmgACt2hIS1DBana7h1oLOAQ'),
    (44, 'JONY', 'Ты Пари (ShaHriX Remix)', 'CQACAgIAAxkBAAKkvmlpIiWPKvaRL0kcATVOqUnic0VSAALFmgACt2hIS45hTyelsRJCOAQ'),
    (45, 'JONY', 'Уйдешь (ShaHriX Remix)', 'CQACAgIAAxkBAAKkwGlpIiVmjCDLjrcJslYxizipyV5EAALGmgACt2hISzHJV1qOld7HOAQ'),
    (46, 'KAMBULAT', 'Выпей Меня (ShaHriX Remix)', 'CQACAgIAAxkBAAKkwmlpIjcrbo80NvhBVjLWdVBvNnt6AALHmgACt2hIS88ws23yeHwiOAQ'),
    (47, 'KAMBULAT', 'Душа Устала (ShaHriX Remix)', 'CQACAgIAAxkBAAKkxGlpIjiufVONMVJgEGDz3yWv8fOPAALImgACt2hIS5VtWUjH3QABUDgE'),
    (48, 'KAMBULAT', 'Звездопад (ShaHriX Remix)', 'CQACAgIAAxkBAAKkxmlpIjkeL9YDnDXcgm4qrgqzi4KsAALKmgACt2hISziMg_DbGyM-OAQ'),
    (49, 'KAMBULAT', 'Как Дела (ShaHriX Remix)', 'CQACAgIAAxkBAAKkyGlpIjppfPlHV-YKKX5wtN8iyMo2AALLmgACt2hIS36Fx18E3DXHOAQ'),
    (50, 'KAMBULAT', 'Письма (ShaHriX Remix)', 'CQACAgIAAxkBAAKkymlpIjsup-LVtircw1dqU418C199AALMmgACt2hIS5nX8P6QcGdLOAQ'),
    (51, 'KONFUZ', 'Аккорды (ShaHriX Remix)', 'CQACAgIAAxkBAAKkzGlpIk2SEAKZzqXxG16FF3QFghiQAALPmgACt2hIS8321x82DcBKOAQ'),
    (52, 'KONFUZ', 'Война (ShaHriX Remix)', 'CQACAgIAAxkBAAKkzmlpIk5nm19UdWwQusnlLREAARiDJQAC0JoAArdoSEuHiJKAIVCMFTgE'),
    (53, 'KONFUZ', 'Касаюсь (ShaHriX Remix)', 'CQACAgIAAxkBAAKk0GlpIk_Jyl-RUWKtM1Gn3KUyVbAMAALRmgACt2hISwlgnOlrRKBtOAQ'),
    (54, 'KONFUZ', 'Не Смотри (ShaHriX Remix)', 'CQACAgIAAxkBAAKk0mlpIlB0B0GLhaa2YrO5KlYo3mfSAALSmgACt2hIS_IyMo0mYWkbOAQ'),
    (55, 'KONFUZ', 'Очень-Очень (ShaHriX Remix)', 'CQACAgIAAxkBAAKk1GlpIlEk6dC19KpPw5Wf-lyTRY4fAALUmgACt2hISz9qAchvlG1XOAQ'),
    (56, 'KONFUZ', 'Пропал Интерес (ShaHriX Remix)', 'CQACAgIAAxkBAAKk1mlpIlF0b_8iGck2C_bzX6uWSfUEAALVmgACt2hIS7DMRPig-erbOAQ'),
    (57, 'KONFUZ', 'Пропал Интерес (ShaHriX Slowed Remix)', 'CQACAgIAAxkBAAKk2GlpIlK5Sk7pg1fXDr3B-Txz5kXvAALWmgACt2hIS5HT4upGYAdBOAQ'),
    (58, 'KONFUZ', 'Ратата (ShaHriX Remix)', 'CQACAgIAAxkBAAKk2mlpIlMf2hNIxhkkcfL-hW_ae8aJAALXmgACt2hISx1z_1SyFtAXOAQ'),
    (59, 'KONFUZ', 'Ратата (ShaHriX Slowed Remix)', 'CQACAgIAAxkBAAKk3GlpIlRT2nYO_x0po5TUl_X7QtRQAALYmgACt2hIS_DaqqihK8njOAQ'),
    (60, 'KONFUZ', 'Рокстар (ShaHriX Remix)', 'CQACAgIAAxkBAAKk3mlpIlQn_DThBjxZLl9cGoqSA0gpAALZmgACt2hIS8aCKTQhkwABITgE'),
    (61, 'KONFUZ', 'Сказка (ShaHriX Remix)', 'CQACAgIAAxkBAAKk4GlpIlUcstXE8IeahUkPpGpZfAABCgAC2poAArdoSEudYWj_N1LcxjgE'),
    (62, 'LELY45', 'Моя душа (ShaHriX Remix)', 'CQACAgIAAxkBAAKk4mlpInhaM-NLpudxAAGLmpawXO11UwAC3ZoAArdoSEu-JAV-5f4NOTgE'),
    (63, 'LIMBA', 'X.O (ShaHriX Remix)', 'CQACAgIAAxkBAAKk5GlpIoBMMhCwjykUdO03ia38vydUAALemgACt2hIS91q5Fak3TPKOAQ'),
    (64, 'LIMBA', 'Секрет (ShaHriX Remix)', 'CQACAgIAAxkBAAKk5mlpIoHJ2LG1DHifqatTmcxOSmrrAALfmgACt2hIS8Abo9ZoAxM8OAQ'),
    (65, 'LXE', 'Девочка Наркотик (ShaHriX Remix)', 'CQACAgIAAxkBAAKk6GlpIo_HsLvg-0k29Ddd-kU5oMkHAALgmgACt2hIS0BSJbX4O721OAQ'),
    (66, 'MACAN', 'IVL (ShaHriX Remix)', 'CQACAgIAAxkBAAKk6mlpIpgrb_-6faEZMJ-HNvQ0xJ9NAALhmgACt2hISyU5QQz7V1_pOAQ'),
    (67, 'MACAN', 'Memories (ShaHriX Remix)', 'CQACAgIAAxkBAAKk7GlpIpnf07MtpANTw3cXGP4RztQWAALimgACt2hIS39X0l9Y5KICOAQ'),
    (68, 'MACAN', 'MP3 (ShaHriX Remix)', 'CQACAgIAAxkBAAKk7mlpIprx24hASsmWBvF0Rj6n_mzfAALjmgACt2hIS6ACMDVAMf2XOAQ'),
    (69, 'MACAN', 'Май (ShaHriX Remix)', 'CQACAgIAAxkBAAKk8GlpIpr6daUvJQ8LpTJY8wIi0gL4AALkmgACt2hIS6bcKm7j0GV-OAQ'),
    (70, 'MACAN', 'Попоплам (ShaHriX Remix)', 'CQACAgIAAxkBAAKk8mlpIptjEif1ik7eqaKmqTTG4S7SAALlmgACt2hIS0-r3g69n4d3OAQ'),
    (71, 'MAKSIM', 'Отпускаю (ShaHriX Remix)', 'CQACAgIAAxkBAAKk9GlpIqXX7E1eYA3v9v1LYpwL93KkAALmmgACt2hIS1jIg5Y-pgdqOAQ'),
    (72, 'MARKUL', 'Стрелы (ShaHriX Remix)', 'CQACAgIAAxkBAAKk9mlpIrSPlGp4SEyQIMhYo956ETB0AALomgACt2hIS3KzTWlxKMgEOAQ'),
    (73, 'MARKUL', 'Я в моменте (ShaHriX Remix)', 'CQACAgIAAxkBAAKk-GlpIrTozfvKSJALKWF_o1zznL9PAALpmgACt2hISzXO_81gkR1aOAQ'),
    (74, 'MIYAGI', 'All The Time (ShaHriX Remix)', 'CQACAgIAAxkBAAKk-mlpIsJAO3-as5NSCkqGQuxSgemqAALrmgACt2hIS-_vQTTw2nPXOAQ'),
    (75, 'MIYAGI', 'Angel (ShaHriX Remix)', 'CQACAgIAAxkBAAKk_GlpIsNvRAQ9i-fU2cepLuWJYQLvAALsmgACt2hIS9OwwCcAAdcOQDgE'),
    (76, 'MIYAGI', 'Marmelade (ShaHriX Remix)', 'CQACAgIAAxkBAAKk_mlpIsRbBEKg-gABP_rdjDEa0IvDlAAC7ZoAArdoSEtnGDrZMeS-9DgE'),
    (77, 'MIYAGI', 'Голгофа (ShaHriX Remix)', 'CQACAgIAAxkBAAKlAAFpaSLFLvHmdcCEliEE8U_F7rRVeAAC7poAArdoSEtcg0vtPoiDJzgE'),
    (78, 'MIYAGI', 'Патрон (ShaHriX Remix)', 'CQACAgIAAxkBAAKlAmlpIsa5g532fQrZqH_QqFYOCDYUAALvmgACt2hIS0Nl5WoxhgvlOAQ'),
    (79, 'MIYAGI', 'Санавабич (ShaHriX Remix)', 'CQACAgIAAxkBAAKlBGlpIsdm4HS5wnNDrSrWPURJksV3AALwmgACt2hIS7F7d5lrJ5n3OAQ'),
    (80, 'MIYAGI', 'Там Ревели Горы (ShaHriX Remix)', 'CQACAgIAAxkBAAKlBmlpIscWgEeBVTPZxXhnV_eBmOjhAALxmgACt2hIS2MLJB1YcEY1OAQ'),
    (81, 'MONA', 'Черная Любовь (ShaHriX Remix)', 'CQACAgIAAxkBAAKlCGlpItlBcaK56w_1anRon18jt7a4AALymgACt2hIS7smSZlzw5rZOAQ'),
    (82, 'MONEYKEN', 'Она Не Любит Вино (ShaHriX Remix)', 'CQACAgIAAxkBAAKlCmlpIuOFiqlN_LAnGEfk22Dd-SRhAALzmgACt2hIS5P-ODeuwRhMOAQ'),
    (83, 'MORGENSHTERN', 'Cristal & МОЁТ (ShaHriX Remix)', 'CQACAgIAAxkBAAKlDGlpIvBqzcOOEZhClGAVRr3j0mzmAAL1mgACt2hIS53TdFTxtDESOAQ'),
    (84, 'MORGENSHTERN', 'Leck (ShaHriX Remix)', 'CQACAgIAAxkBAAKlDmlpIvApUUg2ZCGzrNxMy2Gb82Y9AAL2mgACt2hIS7LdhKKCxeckOAQ'),
    (85, 'MORGENSHTERN', 'Family (ShaHriX Remix)', 'CQACAgIAAxkBAAKlEGlpIvF9ApN0W3AzFCuN0AWqL8sJAAL3mgACt2hIS1R2qeofXQY0OAQ'),
    (86, 'MORGENSHTERN', 'SHOW (ShaHriX Remix)', 'CQACAgIAAxkBAAKlEmlpIvJ_IkcJ0qHTCyh_mC8woleWAAL4mgACt2hISx7XSxW3fp42OAQ'),
    (87, 'MR LAMBO', 'Чилим (ShaHriX Remix)', 'CQACAgIAAxkBAAKlFGlpIwAB9d6iI6wz3cvmO1kl4h1HZwAC-poAArdoSEsHPVGh4a7nWTgE'),
    (88, 'NEKI', 'Мысли (ShaHriX Remix)', 'CQACAgIAAxkBAAKlFmlpIwxxBPdFV2nkFqd8DuRhwJ3qAAL9mgACt2hIS0E1OdvNFu9KOAQ'),
    (89, 'NEKI', 'Огни (ShaHriX Remix)', 'CQACAgIAAxkBAAKlGGlpIw1Pd6j_mND5C_9f04vhxrSsAAL-mgACt2hIS__noHh_U1XuOAQ'),
    (90, 'NLO', 'Не Грусти (ShaHriX Remix)', 'CQACAgIAAxkBAAKlGmlpIxzpaD011Iua7lq0GzYwiM8cAAIBmwACt2hIS-DtE6e4D1tROAQ'),
    (91, 'PUSSYKILLER', 'Франция (ShaHriX Remix)', 'CQACAgIAAxkBAAKlHGlpIyZkv3iRSLTxLbQrD3GTEPe0AAIDmwACt2hISxxrnkkM7_VSOAQ'),
    (92, 'PUSSYKILLER', 'Целуй (ShaHriX Remix)', 'CQACAgIAAxkBAAKlHmlpIyYnQiz1CKqJKarwq7Rvj9c3AAIEmwACt2hIS2p0GSjJNYeNOAQ'),
    (93, 'RAIKAHO', 'Девочка Наркотик (ShaHriX Remix)', 'CQACAgIAAxkBAAKlIGlpIzF9wBRQ16vSf4PXbpR4dccXAAIFmwACt2hIS_Qw-_cSsqFzOAQ'),
    (94, 'RAKHIM', 'Аккорды (ShaHriX Remix)', 'CQACAgIAAxkBAAKlImlpI0BXblKZ85gRhzH7NROZ4l53AAIGmwACt2hIS-0mmegi7wABMjgE'),
    (95, 'RAKHIM', 'Синий Lamborghini (ShaHriX Remix)', 'CQACAgIAAxkBAAKlJGlpI0HKRXGuQe6bVAbxp91s1gFZAAIHmwACt2hISxs86s7GFY0aOAQ'),
    (96, 'RAKHIM', 'Уйдешь (ShaHriX Remix)', 'CQACAgIAAxkBAAKlJmlpI0HFPJsMqlapEGDPcS5B9RpzAAIImwACt2hIS1PhlOIT6x2kOAQ'),
    (97, 'RAMIL', 'MP3 (ShaHriX Remix)', 'CQACAgIAAxkBAAKlKGlpI03DDAzKHrg36mDa-dCaqVOUAAIKmwACt2hIS1Pzd3Fyx2l1OAQ'),
    (98, 'RAMIL', 'Аромат (ShaHriX Remix)', 'CQACAgIAAxkBAAKlKmlpI06rqM9Rh1TXbV_nYyfmgdOGAAILmwACt2hIS7YFsGyKyG1hOAQ'),
    (99, 'RAMIL', 'Дождь (ShaHriX Remix)', 'CQACAgIAAxkBAAKlLGlpI04eGtI1fL_e14bAX4yPpPvjAAIMmwACt2hIS2PQKlhr1hdQOAQ'),
    (100, 'RAMIL', 'Маяк (ShaHriX Remix)', 'CQACAgIAAxkBAAKlLmlpI0883PGzoQmY4LmUnMLFwjnuAAINmwACt2hIS_VFcTxgApP5OAQ'),
    (101, 'RAMIL', 'Просто Лети (ShaHriX Remix)', 'CQACAgIAAxkBAAKlMGlpI0_qMM0Yrb8-GWBeoJQF-pqZAAIOmwACt2hIS59Ghi8AAX_UyTgE'),
    (102, 'RAMIL', 'Сияй (ShaHriX Remix)', 'CQACAgIAAxkBAAKlMmlpI1BsBNfEF_QSBrIWiH_qq9vhAAIPmwACt2hIS4CEIa1Zj7WsOAQ'),
    (103, 'RAMIL', 'Сон (ShaHriX Remix)', 'CQACAgIAAxkBAAKlNGlpI1GDUigYHx3qhuNRBBUNI5mqAAIQmwACt2hIS-TNJeSdp1SQOAQ'),
    (104, 'RAMIL', 'Увидимся (ShaHriX Remix)', 'CQACAgIAAxkBAAKlNmlpI1KsCslrbp-gqtxst88mFndMAAIRmwACt2hIS568gfQn4ndTOAQ'),
    (105, 'RAUF & FAIK', '5 Минут (ShaHriX Remix)', 'CQACAgIAAxkBAAKlOGlpI2_ZpMjPHFVpanEZ63psoRjtAAIUmwACt2hIS7WpCbFFSllAOAQ'),
    (106, 'RAUF & FAIK', 'Деньги и Счастье (ShaHriX Remix)', 'CQACAgIAAxkBAAKlOmlpI3Bj_0qUQGnt8WS3dmvR_bOZAAIVmwACt2hIS-doEtzgyFlsOAQ'),
    (107, 'RAUF & FAIK', 'Я Люблю Тебя Давно (ShaHriX Remix)', 'CQACAgIAAxkBAAKlPGlpI3H73vp2jdNWLNRRfAWBfDLkAAIWmwACt2hISx1RR-lJJjgtOAQ'),
    (108, 'REAL GIRL', 'Вино и Сигареты (ShaHriX Remix)', 'CQACAgIAAxkBAAKlPmlpI4slvAWCyeCGPq7qBqycHXqeAAIXmwACt2hISxZ-f5W24jyROAQ'),
    (109, 'REAL GIRL', 'Всё Для Тебя (ShaHriX Remix)', 'CQACAgIAAxkBAAKlQGlpI4ykLKInQosDZq9iJDV8QqekAAIYmwACt2hIS0WqlLdghmjBOAQ'),
    (110, 'REAL GIRL', 'Девушка Мечты (ShaHriX Remix) (Real Girl Cover)', 'CQACAgIAAxkBAAKlQmlpI43dj259SZ7Ofo6W5xpn91YfAAIZmwACt2hIS8dh5hgDQVP0OAQ'),
    (111, 'REAL GIRL', 'Девушка Мечты (ShaHriX Trap Remix) (Real Girl Cover)', 'CQACAgIAAxkBAAKlRGlpI43ZBr20DsRhKllS3hgLEChPAAIamwACt2hIS7N65exyF9l1OAQ'),
    (112, 'REAL GIRL', 'Девушка Мечты (ShaHriX Remix) (Real Girl Cover) (Full Version)', 'CQACAgIAAxkBAAKlRmlpI47cuR82zJWVREX7Qm-1ocLRAAIbmwACt2hIS6Zu6KtgiotROAQ'),
    (113, 'REAL GIRL', 'Девушка Мечты (ShaHriX Remix) (Real Girl Original Cover)', 'CQACAgIAAxkBAAKlSGlpI4-Rs6RB5IniL6aJpaxtDOoJAAIdmwACt2hIS2L7NU4Zop2dOAQ'),
    (114, 'REAL GIRL', 'Отпускаю (ShaHriX Remix) (Real Girl Cover)', 'CQACAgIAAxkBAAKlSmlpI5AYGZwjwY9B0iuvLgSR30eWAAIemwACt2hIS6OL6QABmzUfBjgE'),
    (115, 'REAL GIRL', 'Послала (ShaHriX Remix)', 'CQACAgIAAxkBAAKlTGlpI5HaPpmVW9gEfcLhHt_FL5IRAAIfmwACt2hIS-HqZ2P2t9joOAQ'),
    (116, 'REAL GIRL', 'Сектор Газа (ShaHriX Remix)', 'CQACAgIAAxkBAAKlTmlpI5KIULIU8DDghvjRDdxu8wFNAAIgmwACt2hIS0GZE9dyvyTZOAQ'),
    (117, 'SCIRENA', 'IVL (ShaHriX Remix)', 'CQACAgIAAxkBAAKlUGlpI633Ue0dWuT9J2AEeaTcU5sJAAIjmwACt2hIS6b1ZGaa12t8OAQ'),
    (118, 'SCIRENA', 'Деньги и Москва (ShaHriX Remix)', 'CQACAgIAAxkBAAKlUmlpI67i4m7NnnyuKFkCqSxf_YTtAAIlmwACt2hISwABUEdEtC4AAZY4BA'),
    (119, 'SLAVA MARLOW', 'Кому Это Надо? (ShaHriX Remix)', 'CQACAgIAAxkBAAKlVGlpI75m_FsH7_unPh9RUTRCoU4EAAImmwACt2hIS2d1mt0DllYaOAQ'),
    (120, 'SLAVA MARLOW', 'Ты Горишь Как Огонь (ShaHriX Remix)', 'CQACAgIAAxkBAAKlVmlpI74DtQ9tEnknWiqR_J8Qa2ZcAAInmwACt2hIS8rHU7idqrXNOAQ'),
    (121, 'SLAVIK POGOSOV', 'Монро (ShaHriX Remix)', 'CQACAgIAAxkBAAKlWGlpI86fFwABhXTQx2fgtolnj0clvAACKZsAArdoSEsyi9Su3mU-CjgE'),
    (122, 'HAMMALI & NAVAI', 'А Если Это Любовь (ShaHriX Remix)', 'CQACAgIAAxkBAAKlWmlpI96dXJ3D3tax_f91lCsK8rzYAAIqmwACt2hISxRw0FI89lCjOAQ'),
    (123, 'HAMMALI & NAVAI', 'Где Ты Была (ShaHriX Remix)', 'CQACAgIAAxkBAAKlXGlpI9-x9theT_y-3mCX6bQSD_tyAAIrmwACt2hIS9udotBhrfYAATgE'),
    (124, 'HAMMALI & NAVAI', 'Девочка танцуй (ShaHriX Remix)', 'CQACAgIAAxkBAAKlXmlpI9-DUMvXyhIDTT8wcyOT92eJAAIsmwACt2hISwTmrzkwf_lFOAQ'),
    (125, 'HAMMALI & NAVAI', 'Наверно Ты Меня Не Помнишь (ShaHriX Remix)', 'CQACAgIAAxkBAAKlYGlpI-A-54bj8Zku_mxPIeuo8uRgAAItmwACt2hIS9AZ827fYfNkOAQ'),
    (126, 'HAMMALI & NAVAI', 'Не Люби Меня (ShaHriX Remix)', 'CQACAgIAAxkBAAKlYmlpI-HypR9__R9jgBH3XBfXe97UAAIumwACt2hIS_MQqsBYft-mOAQ'),
    (127, 'HAMMALI & NAVAI', 'Птичка (ShaHriX Remix)', 'CQACAgIAAxkBAAKlZGlpI-LzBVm7q6kZE0GHfxBlJpDLAAIvmwACt2hISwapEW8uRZ7OOAQ'),
    (128, 'XASSA', 'Дикари (ShaHriX Remix)', 'CQACAgIAAxkBAAKlZmlpJ7HVOvwHegABdiLcZzyNYbMhngACc5sAArdoSEu19SEL-SWfrDgE'),
    (129, 'XCHO', 'All Right (ShaHriX Remix)', 'CQACAgIAAxkBAAKlaGlpJ7w1iR7vC9yK__tHFP2Z7o4gAAJ2mwACt2hIS8wUr0S-ArRjOAQ'),
    (130, 'XCHO', 'Memories (ShaHriX Remix)', 'CQACAgIAAxkBAAKlamlpJ7zUC4Da41_NPXHf5m9WkW0jAAJ3mwACt2hIS5QBCyhmCjkvOAQ'),
    (131, 'XCHO', 'Мысли (ShaHriX Remix)', 'CQACAgIAAxkBAAKlbGlpJ76zEeItns3SPzvEHd1ig53cAAJ4mwACt2hIS34YvqlEYc3COAQ'),
    (132, 'XCHO', 'Поэт (ShaHriX Remix)', 'CQACAgIAAxkBAAKlbmlpJ8P0xmDWP0p8PvvqcH3SF_kAA3qbAAK3aEhLJ_tQaD4zLgk4BA'),
    (133, 'АИГЕЛ', 'Пыяла (ShaHriX Remix)', 'CQACAgIAAxkBAAKlcGlpKVAdocRhvjXfpjmII-Cf0tTrAAKrmwACt2hIS7P92yA8_ycFOAQ'),
    (134, 'АНЕТ САЙ', 'Слезы (ShaHriX Remix)', 'CQACAgIAAxkBAAKlcmlpKWTrHq7JkWZNVr88PJt2CaG2AAKtmwACt2hISw5A4rcwrYNPOAQ'),
    (135, 'АРКАЙДА', 'Дай Дыма Брат (ShaHriX Remix)', 'CQACAgIAAxkBAAKldGlpKXH1MYRsGWrXGodaDW2U8N-RAAKvmwACt2hIS_yYFfPdhSVEOAQ'),
    (136, 'ДЖАРАХОВ', 'Я в моменте (ShaHriX Remix)', 'CQACAgIAAxkBAAKldmlpKYEa9ZlTHjrIXnbErbXIGGGpAAKwmwACt2hISyq7-yY8XcmWOAQ'),
    (137, 'ЕГОР КРИД', '(Не)Идеальна (ShaHriX Remix)', 'CQACAgIAAxkBAAKleGlpKYuoOVz998Xglp0ss88w2h9YAAKymwACt2hIS7999V13-FZtOAQ'),
    (138, 'ЕГОР КРИД', 'We Gotta Get Love (ShaHriX Remix)', 'CQACAgIAAxkBAAKlemlpKYuiOxq-F7Wfbsc-ocpYLUeNAAKzmwACt2hISzjmLLUqUNAjOAQ'),
    (139, 'ЕГОР КРИД', 'Отпускаю (ShaHriX Remix)', 'CQACAgIAAxkBAAKlfGlpKYxtp6pBvxvSFbbigvrZOHA6AAK0mwACt2hIS6tFSlJt74X1OAQ'),
    (140, 'КАНГИ', 'Возьми Сердце Моё (ShaHriX Remix)', 'CQACAgIAAxkBAAKlfmlpKZpNNK2dY8EPXlXgQWWiNxmrAAK2mwACt2hISxDir4UO04e2OAQ'),
    (141, 'КАНГИ', 'Голова (ShaHriX Remix)', 'CQACAgIAAxkBAAKlgGlpKZuZ4ctCqTqzl-LvYUL38yqfAAK3mwACt2hIS1yAnZ8WWBRYOAQ'),
    (142, 'КАНГИ', 'Жить Не Запретишь (ShaHriX Remix)', 'CQACAgIAAxkBAAKlgmlpKZtOT6o9PJvy3Uz6mFF-4X6EAAK4mwACt2hIS_1-yegnO-fkOAQ'),
    (143, 'КАНГИ', 'Эйя (ShaHriX Remix)', 'CQACAgIAAxkBAAKlhGlpKZzhUTHXwgKbeP1osjYOc7yCAAK5mwACt2hIS4IBe75Xv877OAQ'),
    (144, 'КАСПИЙСКИЙ ГРУЗ', 'На белом (ShaHriX Remix)', 'CQACAgIAAxkBAAKlhmlpKaejKTCyAdsldQfEAgABW9IpXQACu5sAArdoSEvUqIY04qlbkDgE'),
    (145, 'КЛАВА КОКА', 'Костер (ShaHriX Remix)', 'CQACAgIAAxkBAAKliGlpKbanAbBjhpP-Yjb15W-hn7rnAAK-mwACt2hISz9cxK0ekXBKOAQ'),
    (146, 'КОСТА ЛАКОСТА', 'Бронежилет (ShaHriX Remix)', 'CQACAgIAAxkBAAKlimlpKbwrK5p4NjV3S9KO4bBjnJ5PAAK_mwACt2hIS_LhFZfBEao5OAQ'),
    (147, 'КРИСПИ', 'Целуй (ShaHriX Remix)', 'CQACAgIAAxkBAAKljGlpKcuV8I4hqXr3H2vzYPJItWufAALAmwACt2hIS2p7i3MdFKS_OAQ'),
    (148, 'КУЧЕР', 'По Щекам Слезы (ShaHriX Remix)', 'CQACAgIAAxkBAAKljmlpKdYh0bP59U9sBS7dLlXxvPcsAALCmwACt2hIS_bkE0_V4sO2OAQ'),
    (149, 'КУЧЕР', 'Се Ля Ви (ShaHriX Remix)', 'CQACAgIAAxkBAAKlkGlpKddP0icIQFTW1ZubDI3dKuEXAALDmwACt2hISy1j3Ya8eliGOAQ'),
    (150, 'РАЙДА', 'Baby Mama (ShaHriX Remix)', 'CQACAgIAAxkBAAKlkmlpKeHbnxio7r21ZjLbIlHnHoOoAALGmwACt2hISxsjt8sLZVK6OAQ'),
    (151, 'СКРИПТОНИТ', 'Baby Mama (ShaHriX Remix)', 'CQACAgIAAxkBAAKllGlpKeztTawzgdyNHOv3w9QFM0U4AALHmwACt2hIS3wz-g2sIB4COAQ'),
    (152, 'СКРИПТОНИТ', 'Чистый (ShaHriX Remix)', 'CQACAgIAAxkBAAKllmlpKe2lihJ-hdK53vxwZ-U_CbdAAALImwACt2hIS8qpvKuewQ9NOAQ'),
    (153, 'СУЛТАН ЛАГУЧЕВ', 'Горький Вкус (ShaHriX Remix)', 'CQACAgIAAxkBAAKlmGlpKfkPh_i5-9NruJ6vMgSDgpYfAALKmwACt2hIS2TBOabnUqJdOAQ'),
    (154, 'СУЛТАН ЛАГУЧЕВ', 'Не Души (ShaHriX Remix)', 'CQACAgIAAxkBAAKlmmlpKfkpNM5k178ypaDwdB8JOlIPAALLmwACt2hIS1VoEZhRHCvcOAQ'),
    (155, 'ЭЛДЖЕЙ', 'Harakiri (ShaHriX Remix)', 'CQACAgIAAxkBAAKlnGlpKgeO7REPkNOaIs9tR8jSMpHXAALOmwACt2hISwABQrzJ889TOjgE'),
    (156, 'ЭЛДЖЕЙ', 'Бронежилет (ShaHriX Remix)', 'CQACAgIAAxkBAAKlnmlpKgjJQzNr67i3GZs4Civr4QuiAALPmwACt2hIS_6myst2Ws07OAQ')
ON CONFLICT (id) DO UPDATE SET
    artist = EXCLUDED.artist,
    name = EXCLUDED.name,
    path = EXCLUDED.path;

SELECT setval(pg_get_serial_sequence('russian', 'id'), COALESCE((SELECT MAX(id) FROM russian), 1), true);

INSERT INTO english (id, artist, name, path) VALUES
    (1, 'BLACKBEAR', 'blackbear - idfc [aibek berkimbaev & shahrix remix]', 'CQACAgIAAxkBAAKjgmlo3rH09LrJcGt6Ytmwjf7T9RhzAALMlQACt2hIS4_Otv1OMoKpOAQ'),
    (2, 'CASSETTE', 'My Way (ShaHriX Remix)', 'CQACAgIAAxkBAAKjhGlo3tVJjt-wnb1Nbk5-RFwhD4IlAALQlQACt2hIS5vE5PArgklhOAQ'),
    (3, 'DAFT PUNK', 'Get Lucky (ShaHriX Remix)', 'CQACAgIAAxkBAAKjhmlo3v8Ym-CHe0oel6lcOxgrY8Z2AALVlQACt2hIS4LBGywO_sp1OAQ'),
    (4, 'DUA LIPA', 'No Lie (ShaHriX & Camron Remix)', 'CQACAgIAAxkBAAKjiGlo3ynGKwUvNBKXaGond3QH846mAALalQACt2hISzQcSHIP2SezOAQ'),
    (5, 'FOUSHEE', 'Deep End (ShaHriX Remix)', 'CQACAgIAAxkBAAKjimlo3z_uQhHwXlR_fMwrQBKUqqSyAALclQACt2hIS_za1UnSSwIZOAQ'),
    (6, 'G-EASY', 'Him & I (ShaHriX & Melix Remix)', 'CQACAgIAAxkBAAKjjGlo30tGHQURszcnh9FgHE9KRG5XAALdlQACt2hIS8bRPIppDbDdOAQ'),
    (7, 'GHOSTLY KISSES', 'Ghostly Kisses - Empty Note (Aibek Berkimbaev & ShaHriX Remix)', 'CQACAgIAAxkBAAKjjmlo31YXg5IT-eGd4-bi2utD57ZVAALglQACt2hIS_uVmehZunh5OAQ'),
    (8, 'IAN STORM', 'Run Away (ShaHriX Remix)', 'CQACAgIAAxkBAAKjkmlo4LAkWGANLpBEMLmo62a_hKqeAAL0lQACt2hISwNI_94Sj-P5OAQ'),
    (9, 'INNA', 'Lonely (ShaHriX Remix)', 'CQACAgIAAxkBAAKjlGlo4LcxaBoC6US05uqS6yLeyeThAAL1lQACt2hIS9FFlemERDaSOAQ'),
    (10, 'INNA', 'Solo (ShaHriX Remix)', 'CQACAgIAAxkBAAKjlmlo4Lvgc7-PNUUHn7HXEd_lc8ILAAL2lQACt2hIS9T3ihSi2WRnOAQ'),
    (11, 'JVLA', 'Such A Whole Remix', 'CQACAgIAAxkBAAKjmGlo4MKZwciotzjRxa-md61TDqoyAAL3lQACt2hIS-pLZL0LCvXdOAQ'),
    (12, 'KINA', 'Kina - Get You The Moon (ShaHriX & Amalee Remix)', 'CQACAgIAAxkBAAKjmmlo4MwZAYeiUFTDl-r3y49GOP7MAAL4lQACt2hISzKu8AzMRTtGOAQ'),
    (13, 'LADY GAGA', 'Bloody Mary (ShaHriX Remix)', 'CQACAgIAAxkBAAKjnGlo4NPgwZ32kW89LknEo7LHHgETAAL6lQACt2hIS2PMfA1P9szGOAQ'),
    (14, 'LISA', 'Money (ShaHriX & TheBlvcks  Remix)', 'CQACAgIAAxkBAAKjnmlo4NwAAWmfGQEcROhmrVnhQObrwAAC-5UAArdoSEtelyQsTC8YnjgE'),
    (15, 'MINELLI', 'Rampampam (ShaHriX Remix)', 'CQACAgIAAxkBAAKjoGlo4OLgaoMuyEpKfQQD1A_Z70FHAAL8lQACt2hIS9k2olFa9gTwOAQ'),
    (16, 'MISHLAWI', 'All Night (ShaHriX & JustBlack$ Remix)', 'CQACAgIAAxkBAAKjomlo4Op0k-j4gizVb61nTSPebJxBAAL9lQACt2hIS0LEMPh5lPuoOAQ'),
    (17, 'OLIVER TREE', 'Cowboys Dont Cry (ShaHriX & UNPY Remix)', 'CQACAgIAAxkBAAKjpGlo4P0m566rb4sJRDVIX1gqEUOyAAL_lQACt2hIS0ewIOc0I8IbOAQ'),
    (18, 'PHARELL WILLIAMS', 'Get Lucky (ShaHriX Remix)', 'CQACAgIAAxkBAAKjpmlo4QYCcXyBkeBzhawcWzKiC7bvAAIBlgACt2hISwbnYoQmLNL2OAQ'),
    (19, 'SEAN PAUL', 'Go Down Deh (ShaHriX & TheBlvcks Remix) (2)', 'CQACAgIAAxkBAAKjqGlo4Ra1RjkU4a_5QCd9VQzlxxSkAAIDlgACt2hIS7kvrLguorc5OAQ'),
    (20, 'SEAN PAUL', 'No Lie (ShaHriX & Camron Remix)', 'CQACAgIAAxkBAAKjqmlo4RoaHnSyNIlKOEZdUI5daePUAAIFlgACt2hIS6hF7K8d_DSIOAQ'),
    (21, 'SQUID GAME', 'Pink Soldiers (ShaHriX Remix)', 'CQACAgIAAxkBAAKjsGlo4Ual-rpLhxlJomSgHUidYsglAAIPlgACt2hIS4cm1OVEbjK-OAQ'),
    (22, 'SZA', 'Big Boy (ShaHriX Remix)', 'CQACAgIAAxkBAAKjsmlo4UxrGJ3qlaWXc-WfKvg97tIkAAIRlgACt2hISzVgVJezCTM4OAQ'),
    (23, 'TIESTO', 'The Business (ShaHriX Remix)', 'CQACAgIAAxkBAAKjtGlo4VOt_9bwFGUTxFWBFceEsps2AAITlgACt2hIS0TauUJ1srofOAQ'),
    (24, 'TREVOR DANIEL', 'Trevor Daniel & Selena Gomez - Past Life (ShaHriX Remix)', 'CQACAgIAAxkBAAKjtmlo4Vd6qaLdjYgj0OSK0YfFPSNSAAIUlgACt2hIS_WLijaDS_PZOAQ'),
    (25, 'XXXTENTACION', 'Bad (ShaHriX & JustBlack$ Remix)', 'CQACAgIAAxkBAAKjuGlo4V3KRsjD8yz2tEt33PrKtGBCAAIWlgACt2hIS0rjlONF5taDOAQ')
ON CONFLICT (id) DO UPDATE SET
    artist = EXCLUDED.artist,
    name = EXCLUDED.name,
    path = EXCLUDED.path;

SELECT setval(pg_get_serial_sequence('english', 'id'), COALESCE((SELECT MAX(id) FROM english), 1), true);

